apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: lukasnys/kube-web-api:stable
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-service
spec:
  type: NodePort
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      