apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalama-deployment
  labels:
    app: scalama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scalama
  template:
    metadata:
      labels:
        app: scalama
    spec:
      containers:
      - name: scalama
        image: lukasnys/scalama:stable
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: scalama-service
spec:
  type: NodePort
  selector:
    app: scalama
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      
